using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using RetailPulse.Api.Configuration;
using RetailPulse.Api.Rag;
using RetailPulse.Contracts.Rag;

namespace RetailPulse.Tests.Rag.Baselines;

/// <summary>
/// Byte-for-byte pre-Wave-5 regression baseline for the InMemory BM25 knowledge
/// provider. This is the executable proof of the Wave 5 optionality guarantee:
///
///     "Default-configuration behaviour is byte-for-byte identical to
///      pre-Wave-5 behaviour on a fixed query corpus."
///
/// Baseline provenance:
/// <list type="bullet">
///   <item>The pre-Wave-5 BM25 scoring kernel lives at commit
///     <c>c4481de</c> (parent of the #102 abstraction-layer commit).</item>
///   <item>A byte-diff between <c>c4481de:src/RetailPulse.Api/Rag/InMemoryKnowledgeBase.cs</c>
///     and <c>HEAD</c> confirmed the BM25 loop, IDF math, tokenizer, chunker
///     constants, and unscoped SearchAsync path are unchanged — the only
///     additions since c4481de are (a) a sources-filter overload that
///     short-circuits above the scoring loop, (b) capability/probe methods,
///     and (c) a stable ProviderName constant. None of those alter the
///     unscoped scoring output.</item>
///   <item>The golden fixture <c>inmemory-pre-wave5.json</c> was generated by
///     running the CURRENT <see cref="InMemoryKnowledgeBase"/> against
///     <see cref="PreWave5BaselineFixture"/> and rounding scores to 6
///     decimals for cross-platform determinism. A diff of the JSON on any
///     later PR is therefore evidence of a scoring-kernel change and MUST
///     be reviewed as a behavioural break.</item>
/// </list>
///
/// To regenerate deliberately (rare — only after an intentional BM25 change),
/// set <c>RETAIL_PULSE_REGEN_BM25_BASELINE=1</c> and run this test. Otherwise
/// the test asserts current output matches the pinned bytes exactly.
/// </summary>
public sealed class PreWave5InMemoryBaselineTests
{
    private const string BaselineFileName = "inmemory-pre-wave5.json";
    private const string RegenEnvVar = "RETAIL_PULSE_REGEN_BM25_BASELINE";
    private const int ScoreDecimals = 6;

    [Fact]
    public async Task InMemoryBM25_MatchesPreWave5Baseline_ByteForByte()
    {
        InMemoryKnowledgeBase kb = new(
            NullLoggerFactory.Instance.CreateLogger<InMemoryKnowledgeBase>(),
            Options.Create(new KnowledgeOptions()));

        // Fixed ingestion order — BM25 corpus statistics depend on ingestion
        // set membership, not ingestion order, but the test pins the order
        // anyway so any accidental order-sensitivity would be surfaced too.
        foreach ((string title, string source, string content) in PreWave5BaselineFixture.Corpus)
        {
            await kb.IngestDocumentAsync(title, content, source);
        }

        var actual = new BaselineDocument
        {
            FixtureVersion = PreWave5BaselineFixture.FixtureVersion,
            BaselineOrigin = "commit c4481de (parent of #102) - see class remarks",
            Queries = [],
        };

        foreach (string query in PreWave5BaselineFixture.Queries)
        {
            IReadOnlyList<SearchResult> hits = await kb.SearchAsync(query, topK: 5);
            // Deterministic tie-break for baseline serialization only: the
            // provider is free to return tied-score hits in any stable
            // order (ConcurrentDictionary iteration is unordered), so the
            // baseline captures the RESULT SET and score bytes rather than
            // the incidental tie-order. Ranking on distinct scores is still
            // fully asserted because the sort key is score-first.
            IEnumerable<SearchResult> ordered = hits
                .OrderByDescending(h => h.Score)
                .ThenBy(h => h.Title, StringComparer.Ordinal)
                .ThenBy(h => h.Source, StringComparer.Ordinal)
                .ThenBy(h => h.ChunkIndex);
            var queryResult = new BaselineQueryResult
            {
                Query = query,
                Hits = [.. ordered.Select(h => new BaselineHit
                {
                    Title = h.Title,
                    Source = h.Source,
                    ChunkIndex = h.ChunkIndex,
                    Score = Math.Round(h.Score, ScoreDecimals, MidpointRounding.AwayFromZero),
                })],
            };
            actual.Queries.Add(queryResult);
        }

        string actualJson = SerializeBaseline(actual);

        string baselinePath = ResolveBaselinePath();
        if (string.Equals(Environment.GetEnvironmentVariable(RegenEnvVar), "1", StringComparison.Ordinal))
        {
            // Always write the regenerated baseline back to the source tree
            // so the JSON is picked up on the next build (the CopyToOutputDirectory
            // rule refreshes the assembly-adjacent copy). Writing to the
            // assembly-adjacent copy alone would silently lose the change
            // on the next `dotnet build`.
            string sourceTreePath = LocateInSourceTree(
                Path.Combine("tests", "RetailPulse.Tests", "Rag", "Baselines", BaselineFileName));
            Directory.CreateDirectory(Path.GetDirectoryName(sourceTreePath)!);
            File.WriteAllText(sourceTreePath, actualJson, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            // Fail the test so the regeneration is an intentional two-step
            // that shows up in code review — never a silent overwrite.
            throw new InvalidOperationException(
                $"Regenerated {sourceTreePath}. Re-run tests WITHOUT {RegenEnvVar}=1 to lock the new baseline in.");
        }

        File.Exists(baselinePath).Should().BeTrue(
            $"the pinned baseline {baselinePath} must exist. Regenerate with {RegenEnvVar}=1.");

        string expectedJson = File.ReadAllText(baselinePath);
        expectedJson = NormalizeLineEndings(expectedJson);
        actualJson = NormalizeLineEndings(actualJson);

        // Use raw Assert.Equal to bypass FluentAssertions's failure-message
        // brace-placeholder formatter -- the JSON payload contains {} that
        // would otherwise crash the formatter before the diff is shown.
        Assert.Equal(expectedJson, actualJson);
    }

    [Fact]
    public void PreWave5BM25Kernel_HasNotChanged_StaticSourceContract()
    {
        // Belt-and-suspenders: even if someone regenerated the JSON fixture
        // by accident, this contract catches BM25 kernel edits by looking at
        // the InMemoryKnowledgeBase source directly.
        string sourcePath = ResolveInMemorySourcePath();
        File.Exists(sourcePath).Should().BeTrue($"expected InMemoryKnowledgeBase source at {sourcePath}");
        string src = File.ReadAllText(sourcePath);

        // Standard BM25 constants — a change to any of these is a scoring break.
        src.Should().Contain("private const double _k1 = 1.2;",
            "BM25 k1 constant must remain 1.2 to preserve pre-Wave-5 relevance ranking");
        src.Should().Contain("private const double _b = 0.75;",
            "BM25 b constant must remain 0.75 to preserve pre-Wave-5 relevance ranking");
        src.Should().Contain("private const double _minScoreThreshold = 0.3;",
            "the score threshold controls empty-result semantics used by RagContextProvider");

        // The BM25 scoring loop shape.
        src.Should().Contain("double numerator = tf * (_k1 + 1);",
            "BM25 numerator expression must remain unchanged");
        src.Should().Contain("double denominator = tf + (_k1 * (1 - _b + (_b * chunk.TokenCount / _avgDocLength)));",
            "BM25 denominator expression must remain unchanged");
        src.Should().Contain("score += idf * (numerator / denominator);",
            "BM25 term accumulation must remain unchanged");
        src.Should().Contain("if (score > _minScoreThreshold)",
            "BM25 result threshold gate must remain unchanged");
    }

    private static string SerializeBaseline(BaselineDocument doc)
    {
        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        };
        // Trailing newline so diff tools show clean edits.
        return JsonSerializer.Serialize(doc, options) + "\n";
    }

    private static string NormalizeLineEndings(string s) => s.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string ResolveBaselinePath()
    {
        // Test binaries copy the JSON to the output directory (see .csproj
        // Content Include). The path resolves relative to the assembly.
        string assemblyDir = Path.GetDirectoryName(
            typeof(PreWave5InMemoryBaselineTests).Assembly.Location) ?? AppContext.BaseDirectory;
        string candidate = Path.Combine(assemblyDir, "Rag", "Baselines", BaselineFileName);
        if (File.Exists(candidate))
        {
            return candidate;
        }
        // Fall back to the source tree so `dotnet test` from the repo root also works.
        return LocateInSourceTree(Path.Combine("tests", "RetailPulse.Tests", "Rag", "Baselines", BaselineFileName));
    }

    private static string ResolveInMemorySourcePath() =>
        LocateInSourceTree(Path.Combine("src", "RetailPulse.Api", "Rag", "InMemoryKnowledgeBase.cs"));

    private static string LocateInSourceTree(string relativePath)
    {
        string dir = AppContext.BaseDirectory;
        for (int i = 0; i < 12; i++)
        {
            string candidate = Path.Combine(dir, relativePath);
            if (File.Exists(candidate))
            {
                return candidate;
            }
            string? parent = Path.GetDirectoryName(dir);
            if (parent is null || parent == dir)
            {
                break;
            }
            dir = parent;
        }
        // Best-effort — return the projected path even if missing so the caller
        // can produce a clear error message.
        return Path.Combine(AppContext.BaseDirectory, relativePath);
    }

    private sealed class BaselineDocument
    {
        public string FixtureVersion { get; set; } = string.Empty;
        public string BaselineOrigin { get; set; } = string.Empty;
        public List<BaselineQueryResult> Queries { get; set; } = [];
    }

    private sealed class BaselineQueryResult
    {
        public string Query { get; set; } = string.Empty;
        public List<BaselineHit> Hits { get; set; } = [];
    }

    private sealed class BaselineHit
    {
        public string Title { get; set; } = string.Empty;
        public string Source { get; set; } = string.Empty;
        public int ChunkIndex { get; set; }
        public double Score { get; set; }
    }
}
